---
- name: Master playbook to set up development station
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Show pull directory
      ansible.builtin.debug:
        msg: "Ansible successfully cloned repo into pull dir: {{ playbook_dir }}"

# Run all the child playbooks
# Detect Homebrew prefix to use for all future playbooks
- ansible.builtin.import_playbook: ansible/define-brew-prefix.yml

# # Setup terminal and git for dev station
- ansible.builtin.import_playbook: ansible/terminal-setup.yml
- ansible.builtin.import_playbook: ansible/git-setup.yml

# # Setup dev station using Homebrew
- ansible.builtin.import_playbook: ansible/homebrew-setup.yml

# # Setup terminal for dev station
# - ansible.builtin.import_playbook: ansible/raycast-setup.yml
# - ansible.builtin.import_playbook: ansible/mac-setup.yml