---
- name: Setup raycast for ease of navigation
  hosts: localhost
  vars:
    raycast_config_url: "https://raw.githubusercontent.com/etgonehomie/dev-setup/refs/heads/main/dotfiles/.gitignore_global"
  tasks:
    - name: Download and store the encrypted raycast config file from GitHub
      get_url:
        url: "{{ raycast_config_url }}"
        dest: "{{ ansible_env.HOME }}"
    - name: Import Raycast configuration
      vars:
        rayconfig_file: "{{ ansible_env.HOME }}/raycast_config.rayconfig"  # Name for exported file
      tasks:
        - name: Import Raycast configuration
          ansible.builtin.script: |
            #!/usr/bin/osascript
            tell application "Raycast"
              activate
              tell application "System Events"
                keystroke "," using {command down}  # Open Preferences
                delay 1
                keystroke "Import Preferences & Data"  # Type command
                delay 1
                keystroke return  # Trigger import
                delay 2
                keystroke "/Users/{{ ansible_user_id }}/{{ rayconfig_file }}"  # Set import path
                delay 1
                keystroke return  # Import
                keystroke "Password"  # Input password for encrypted file
                delay 1
                keystroke return  # Finish import
              end tell
            end tell
          args:
            executable: /usr/bin/osascript