# Setup for Mac.
# TODO: Make this dynamic for a linux setup

- name: Set up a development workstation
  hosts: localhost
  # become: true  # Run tasks with sudo
  gather_facts: yes  # don't gather system facts

  vars:
    # Destination system paths
    dotfile_local_dir: "{{ ansible_env.HOME }}/.config"
    git_global_local_dir: "{{ dotfile_local_dir }}/git/.gitignore_global"
    oh_my_posh_themes_local_dir: "{{ dotfile_local_dir }}/oh-my-posh/themes"
    oh_my_posh_theme_filename: 'zen.toml'

    # Source paths of dotfile templates
    gitignore_global_git_url: "https://raw.githubusercontent.com/etgonehomie/dev-setup/refs/heads/main/dotfiles/.gitignore_global"
    gitconfig__global_git_url: "https://raw.githubusercontent.com/etgonehomie/dev-setup/refs/heads/main/dotfiles/.gitignore_global"
    zshrc_git_url: "https://raw.githubusercontent.com/etgonehomie/dev-setup/refs/heads/main/dotfiles/.gitignore_global"
    zshenv_git_url: "https://raw.githubusercontent.com/etgonehomie/dev-setup/refs/heads/main/dotfiles/.gitignore_global"
    oh_my_posh_theme_git_url: "https://raw.githubusercontent.com/etgonehomie/dev-setup/refs/heads/main/zen-mod.toml"
    
    
    tasks_brew_cli:
      - package: curl 
        description: "Allows download of external binaries"
      - package: fzf 
        description: "Allows fuzzy search (and case insensitivity) in terminal"
      - package: bat
        description: "View file content with syntax highlighting (cat replacement)"
      - package: zsh-autosuggestions
        description: "CLI history suggestions"
      - package: zsh-autocomplete
        description: "CLI command autocomplete"
      - package: zsh-fast-syntax-highlighting
        description: "Syntax highlighting for CLI commands"
      - package: neovim
        description: "Terminal text editor (vim replacement)"
      - package: oh-my-posh 
        description: "Prompt theme engine for any shell"
      - package: font-hack-nerd-font 
        description: "Font needed for oh-my-posh to work"

    tasks_brew_dev:
      - package: iterm2
        description: "Terminal GUI replacement"
      - package: git
        description: "Source code management"
      - package: python
        description: "Data Engineer/Science projects"
      - package: node
        description: "JS development"
      - package: docker
        description: "Containerize depoloyments"

    tasks_cask_dev:
      - package: visual-studio-code
        description: "VS Code: IDE"
      - package: raycast
        description: 'Raycast: Mac Finder Replacement'
      - package: postman
        description: "Postman: API Tester"
      - package: sublime-text
        description: "Sublime: Easy text file editor"
      - package: google-chrome
        description: "Chrome Browser"
      - package: firefox
        description: "Firefox Browser"
      - package: vivaldi
        description: "Vivaldi Browser"

  tasks:
    # Install necessary programs
    - name: Install Homebrew ZSH Tools via Loop
      block:
        - name: Install Homebrew ZSH Tools via Loop
          homebrew:
            name: "{{ item.package }}"
            state: present
          loop: "{{ tasks_brew_cli }}"

    - name: Install Homebrew Dev Tools via Loop
      block:
        - name: Install Homebrew Dev Tools via Loop
          homebrew:
            name: "{{ item.package }}"
            state: present
          loop: "{{ tasks_brew_dev }}"

    - name: Install Homebrew Cask Apps via Loop
      block:
        - name: Install Homebrew Cask Apps via Loop
          homebrew_cask:
            name: "{{ item.package }}"
            state: present
            ignore_errors:
          loop: "{{ tasks_cask_dev }}"

    # Setup homebrew to work with CLI plugins
    
    - name: Detect Homebrew prefix dynamically
      ansible.builtin.shell: "brew --prefix"
      register: brew_prefix_result
      changed_when: false  # Read-only check
      become: no

    - name: Set Homebrew prefix fact
      ansible.builtin.set_fact:
        brew_prefix: "{{ brew_prefix_result.stdout }}"

    - name: Remove group/other write perms from dynamic Zsh dir
      ansible.builtin.file:
        path: "{{ brew_prefix }}/share"
        mode: "go-w"  # Removes write for group and others (e.g., 775 -> 755)
        recurse: yes  # Equivalent to -R
      become: yes  # Equivalent to sudo

    # Update terminal files
    - name: Download and store the .zshenv file from GitHub
      get_url:
        url: "{{ zshenv_git_url }}"
        dest: "{{ ansible_env.HOME }}"

    - name: Download and store the .zshrc file from GitHub
      get_url:
        url: "{{ zshrc_git_url }}"
        dest: "{{ ansible_env.HOME }}"

    # Update global git file
    - name: Ensure ~/.config/git dir exists to place all git dotfiles
      file:
        path: "{{ git_global_local_dir }}"
        state: directory

    - name: Download and create the global .gitconfig file from GitHub
      get_url:
        url: "{{ gitconfig_global_git_url }}"
        dest: "{{ git_global_local_dir }}"

    - name: Download and create the global .gitignore file from GitHub
      get_url:
        url: "{{ gitignore_global_git_url }}"
        dest: "{{ git_global_local_dir }}"

    - name: Modify .gitconfig file to use the global .gitignore_global
      git_config:
        name: core.excludesfile
        value: "{{ gitignore_global_path }}/.gitignore_global"
        scope: global

    # TODO: Start from here
    # Update terminal theming using oh-my-posh
    # Leave the theme in brew share dir and just make an ref to that dir in the .config dir
    - name: Ensure ~/[brew-prefix]/share/oh-my-posh/themes dir exists
      file:
        path: "{{ brew_prefix/share/oh-my-posh/themes }}"
        state: directory

    # Can place my theme in a new dir in ~/.config/oh-my-posh and point the zshrc file to this
    # Leave file in brew-share folder to easily find all the other themes if I want to change
    - name: Copy oh-my-posh zen theme and place in brew dir
      get_url:
        url: '{{ oh_my_posh_theme_git_url }}'
        dest: '{{ brew_prefix }}/share/oh-my-posh/themes/{{ oh_my_posh_theme_filename }}'

    - name: Ensure ~/.config/oh-my-posh directory exists
      file:
        path: "{{ ansible_env.HOME }}/.config/oh-my-posh/themes"
        state: directory

    - name: Create a symbolic link for oh_my_posh themes dir
      file:
        src: '{{ brew_prefix | trim }}/share/oh-my-posh/themes'
        dest: "{{ oh_my_posh_themes_local_dir }}"
        state: link