---
- name: Use Homebrew to Install CLI & Dev tools
  hosts: localhost
  vars:
    # Source paths of dotfile templates
    zshenv_git_url: "https://raw.githubusercontent.com/etgonehomie/dev-setup/refs/heads/main/dotfiles/terminal/.zshenv"
    zshrc_git_url: "https://raw.githubusercontent.com/etgonehomie/dev-setup/refs/heads/main/dotfiles/terminal/.zshrc"
    oh_my_posh_theme_git_url: "https://raw.githubusercontent.com/etgonehomie/dev-setup/refs/heads/main/dotfiles/oh-my-posh/themes/zen.toml"

    # Destination system paths
    dotfile_local_dir: "{{ ansible_env.HOME }}/.config"    
    oh_my_posh_themes_local_dir: "{{ dotfile_local_dir }}/oh-my-posh/themes"
    oh_my_posh_theme_filename: 'zen.toml'

  tasks:
    # Update terminal config files
    - name: Download and store the .zshenv file from GitHub
      get_url:
        url: "{{ zshenv_git_url }}"
        dest: "{{ ansible_env.HOME }}"

    - name: Download and store the .zshrc file from GitHub
      get_url:
        url: "{{ zshrc_git_url }}"
        dest: "{{ ansible_env.HOME }}"
  
    # Update terminal theming using oh-my-posh    
    - name: Create dir `~/[brew-prefix]/share/oh-my-posh/themes` if DNE. Place original oh-my-posh themes here
      file:
        path: "{{ brew_prefix }}/share/oh-my-posh/themes"
        state: directory

    - name: Copy oh-my-posh zen theme and place in brew dir
      get_url:
        url: '{{ oh_my_posh_theme_git_url }}'
        dest: '{{ brew_prefix }}/share/oh-my-posh/themes/{{ oh_my_posh_theme_filename }}'

    # Create symlink to themes in .config file for easy reference
    - name: Check if oh_my_posh themes local dir exists
      stat:
        path: "{{ oh_my_posh_themes_local_dir }}"
      register: themes_dir_stat

    - name: Remove oh_my_posh themes local dir if it exists
      file:
        path: "{{ oh_my_posh_themes_local_dir }}"
        state: absent
      when: themes_dir_stat.stat.exists and themes_dir_stat.stat.isdir

    - name: Create a symbolic link for oh_my_posh themes dir (create the dir as well)
      file:
        src: '{{ brew_prefix }}/share/oh-my-posh/themes'
        dest: "{{ oh_my_posh_themes_local_dir }}"
        state: link