---
- name: Detect and set Homebrew prefix fact
  hosts: localhost
  tasks:          
    - name: Detect Homebrew prefix dynamically
      ansible.builtin.shell: "brew --prefix"
      environment:
        PATH: "{{ ansible_env.PATH }}:/opt/homebrew/bin:/usr/local/bin:/home/linuxbrew/.linuxbrew/bin"  # Add likely Homebrew paths
      register: brew_prefix_result
      changed_when: false  # Read-only check
      become: no

    - name: Set Homebrew prefix fact
      ansible.builtin.set_fact:
        brew_prefix: "{{ brew_prefix_result.stdout }}"
        cacheable: yes  # Makes fact available across playbooks in this run