# For example themes and ideas: https://ohmyposh.dev/docs/themes
# To convert json/yaml to toml: https://www.convertsimple.com/convert-json-to-toml/

console_title_template = '{{ .UserName }} @ {{ .HostName }}...{{ .Folder }} ({{ .Shell }})'
version = 3
final_space = true

[secondary_prompt]
  template = '❯❯ '
  foreground = 'magenta'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

# [[blocks]]
#   alignment = "left"
#   newline = true
#   type = "prompt"

#   [[blocks.segments]]
#     background = "#29315A"
#     foreground = "#AEA4BF"
#     leading_diamond = ""
#     style = "diamond"
#     template = "{{ .FormattedMs }}"
#     trailing_diamond = " "
#     type = "executiontime"

#     [blocks.segments.properties]
#       style = "austin"
#       threshold = 150

#   [[blocks.segments]]
#     background = "#29315A"
#     foreground = "#E64747"
#     leading_diamond = ""
#     style = "diamond"
#     template = "{{ .UserName }} ❯"
#     trailing_diamond = ""
#     type = "text"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'
  
  
# Right theme bubble icons
[[blocks]]
  alignment = "right"
  type = "prompt"

  # # Shows current directoy in bubble
  # [[blocks.segments]]
  #   background = "#29315A"
  #   foreground = "#3EC669"
  #   leading_diamond = ""
  #   style = "diamond"
  #   template = " {{ .Path }}"
  #   trailing_diamond = ""
  #   type = "path"

  #   [blocks.segments.properties]
  #     style = "folder"

  # Shows Git status and changes color depending on status
  [[blocks.segments]]
    background = "#29315A"
    foreground = "#43CCEA"
    foreground_templates = [
      "{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}",
      "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}",
      "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
      "{{ if gt .Behind 0 }}#B388FF{{ end }}"
    ]
    leading_diamond = " "
    style = "diamond"
    template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
    trailing_diamond = ""
    type = "git"

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  # Show languages used in current dir 
  [[blocks.segments]]
    background = "#29315A"
    foreground = "#E4F34A"
    leading_diamond = " "
    style = "diamond"
    template = " {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}"
    trailing_diamond = ""
    type = "python"

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    background = "#29315A"
    foreground = "#7FD5EA"
    leading_diamond = " "
    style = "diamond"
    template = "{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
    trailing_diamond = ""
    type = "go"

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    background = "#29315A"
    foreground = "#42E66C"
    leading_diamond = " "
    style = "diamond"
    template = "{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}"
    trailing_diamond = ""
    type = "node"

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    background = "#29315A"
    foreground = "#E64747"
    leading_diamond = " "
    style = "diamond"
    template = "{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
    trailing_diamond = ""
    type = "ruby"

    [blocks.segments.properties]
      fetch_version = false
  
  # # Show remaining battery
  # [[blocks.segments]]
  #   background = "#29315A"
  #   foreground = "#9B6BDF"
  #   foreground_templates = [
  #     "{{if eq \"Charging\" .State.String}}#40c4ff{{end}}",
  #     "{{if eq \"Discharging\" .State.String}}#ff5722{{end}}",
  #     "{{if eq \"Full\" .State.String}}#4caf50{{end}}"
  #   ]
  #   leading_diamond = " "
  #   style = "diamond"
  #   template = "{{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}"
  #   trailing_diamond = ""
  #   type = "battery"

  #   [blocks.segments.properties]
  #     charged_icon = " "
  #     charging_icon = "⇡ "
  #     discharging_icon = "⇣ "


[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
