---
# Use this script to download safe mac config domains
# to use in the main.yml playbook
- name: Backup safe macOS defaults including key bindings and hardware settings
  hosts: localhost
  vars_files:
    - mac-export-vars.yml
  vars:
    backup_dir: "{{ ansible_env.HOME }}/macos_config_backup"
  tasks:
    - name: Create backup directory
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
        mode: "0700"

    - name: Export mac safe defaults to {{ backup_dir }}
      ansible.builtin.shell: "defaults read {{ item.domain }} > {{ backup_dir }}/{{ item.domain | replace('.', '_') }}.txt"
      loop: "{{ mac_safe_domains }}"
      args:
        creates: "{{ backup_dir }}/{{ item.domain | replace('.', '_') }}.txt"