---
- name: Clean-up the cloned dir in .ansible/pull
  hosts: localhost
  vars_files:
    - vars.yml  #  relative path to current playbook
  tasks: 
    - name: Clean-up the cloned dir at {{ root_dir }}
      ansible.builtin.shell: "rm -rf {{ root_dir }}"
      ignore_errors: yes
