---
- name: Use Homebrew to Install CLI & Dev tools
  hosts: localhost
  vars:
    # Source paths of dotfile templates
    gitconfig_global_git_url: "https://raw.githubusercontent.com/etgonehomie/dev-setup/refs/heads/main/dotfiles/git/.gitconfig"
    gitignore_global_git_url: "https://raw.githubusercontent.com/etgonehomie/dev-setup/refs/heads/main/dotfiles/git/.gitignore_global"

    # Destination system paths
    git_global_local_dir: "{{ ansible_env.HOME }}/.config/git"
    # git_global_local_dir: "{{ dotfile_local_dir }}/git/.gitignore_global"

  tasks:
    # Update global git file
    - name: Create dir `~/.config/git` if DNE. Place all git dotfiles here
      file:
        path: "{{ git_global_local_dir }}"
        state: directory

    - name: Download and create the global .gitconfig file from GitHub
      get_url:
        url: "{{ gitconfig_global_git_url }}"
        dest: "{{ git_global_local_dir }}/.gitconfig"

    - name: Download and create the global .gitignore file from GitHub
      get_url:
        url: "{{ gitignore_global_git_url }}"
        dest: "{{ git_global_local_dir }}/.gitignore_global"

    - name: Modify .gitconfig file to use the global .gitignore_global
      git_config:
        name: core.excludesfile
        value: "{{ git_global_local_dir }}/.gitignore_global"
        scope: global

   
