---
- name: Use Homebrew to Install CLI & Dev tools
  hosts: localhost
  vars_files:
    - vars.yml    # relative path to current playbook
  vars:
    # Source paths of dotfile templates
    gitconfig_repo_url: "{{ root_dir }}/dotfiles/git/.gitconfig"
    gitignore_repo_url: "{{ root_dir }}/dotfiles/git/.gitignore_global"

    # Destination system paths
    git_local_dir: "{{ ansible_env.HOME }}/.config/git"

  tasks:
    # Update global git file
    - name: Ensure global git config dir exists at {{ git_local_dir }}
      file:
        path: "{{ git_local_dir }}"
        state: directory

    - name: Copy .gitconfig from {{ root_dir }} to {{ git_local_dir }}
      ansible.builtin.copy:
        src: "{{ gitconfig_repo_url }}"
        dest: "{{ git_local_dir }}/.gitconfig"
        remote_src: yes
        force: yes
    
    - name: Copy .gitignore_global from {{ root_dir }} to {{ git_local_dir }}
      ansible.builtin.copy:
        src: "{{ gitignore_repo_url }}"
        dest: "{{ git_local_dir }}/.gitignore_global"
        remote_src: yes
        force: yes