---
- name: Use Homebrew to Install CLI & Dev tools
  hosts: localhost
  vars_files:
    - homebrew_vars.yml   # relative path to current playbook
  tasks:
    - name: Install Homebrew ZSH Tools via Loop
      block:
        - name: Install {{ item.package }} - {{ item.description }}
          homebrew:
            name: "{{ item.package }}"
            state: present
          loop: "{{ cli_extensions }}"

    - name: Install Homebrew Dev Tools via Loop
      block:
        - name: Install {{ item.package }} - {{ item.description }}
          homebrew:
            name: "{{ item.package }}"
            state: present
          loop: "{{ native_brew_apps }}"

    - name: Install Homebrew Cask Dev Apps via Loop
      block:
        - name: Install {{ item.package }} - {{ item.description }}
          homebrew_cask:
            name: "{{ item.package }}"
            state: present
          ignore_errors: true
          loop: "{{ cask_dev_apps }}"

    - name: Install Homebrew Cask Browsers via Loop
      block:
        - name: Install {{ item.package }} - {{ item.description }}
          homebrew_cask:
            name: "{{ item.package }}"
            state: present
          ignore_errors: true
          loop: "{{ browser_apps }}"

    # This removes error in CLI for Homebrew having too much access
    - name: Remove group/other write perms from dynamic zsh dir
      ansible.builtin.file:
        path: "{{ brew_prefix }}/share"
        mode: "go-w"  # Removes write for group and others (e.g., 775 -> 755)
        recurse: yes  # Equivalent to -R