---
- name: Use Homebrew to Install CLI & Dev tools
  hosts: localhost
  vars:
    tasks_brew_cli:
      - package: curl 
        description: "Allows download of external binaries"
      - package: eza
        description: "A better `ls` command that has colors" 
      - package: fzf 
        description: "Allows fuzzy search (and case insensitivity) in terminal"
      - package: bat
        description: "View file content with syntax highlighting (cat replacement)"
      - package: zsh-autosuggestions
        description: "CLI history suggestions"
      - package: zsh-autocomplete
        description: "CLI command autocomplete"
      - package: zsh-fast-syntax-highlighting
        description: "Syntax highlighting for CLI commands"
      - package: neovim
        description: "Terminal text editor (vim replacement)"
      - package: oh-my-posh 
        description: "Prompt theme engine for any shell"
      - package: font-hack-nerd-font 
        description: "Font needed for oh-my-posh to work"

    tasks_brew_dev:
      - package: iterm2
        description: "Terminal GUI replacement"
      - package: git
        description: "Source code management"
      - package: python
        description: "Data Engineer/Science projects"
      - package: node
        description: "JS development"
      - package: docker
        description: "Containerize depoloyments"

    tasks_cask_dev:
      - package: visual-studio-code
        description: "VS Code: IDE"
      - package: raycast
        description: 'Raycast: Mac Finder Replacement'
      - package: postman
        description: "Postman: API Tester"
      - package: sublime-text
        description: "Sublime: Easy text file editor"
      - package: google-chrome
        description: "Chrome Browser"
      - package: firefox
        description: "Firefox Browser"
      - package: vivaldi
        description: "Vivaldi Browser"
  tasks:
    - name: Install Homebrew ZSH Tools via Loop
      block:
        - name: Install Homebrew ZSH Tools via Loop
          homebrew:
            name: "{{ item.package }}"
            state: present
          loop: "{{ tasks_brew_cli }}"

    - name: Install Homebrew Dev Tools via Loop
      block:
        - name: Install Homebrew Dev Tools via Loop
          homebrew:
            name: "{{ item.package }}"
            state: present
          loop: "{{ tasks_brew_dev }}"

    - name: Install Homebrew Cask Apps via Loop
      block:
        - name: Install Homebrew Cask Apps via Loop
          homebrew_cask:
            name: "{{ item.package }}"
            state: present
          ignore_errors: true
          loop: "{{ tasks_cask_dev }}"

    # This removes error in CLI for Homebrew having too much access
    - name: Remove group/other write perms from dynamic zsh dir
      ansible.builtin.file:
        path: "{{ brew_prefix }}/share"
        mode: "go-w"  # Removes write for group and others (e.g., 775 -> 755)
        recurse: yes  # Equivalent to -R