---
- name: Setup mac configuration settings
  hosts: localhost
  vars_files:
    - vars.yml    # relative path to current playbook
  vars:
    mac_config_dir: "{{ root_dir }}/ansible/macos_config_backup"
    apps_to_kill:
      - "Dock"
      - "Finder"
      - "Terminal"
      - "Raycast"
    apps_to_restart:
      - "Raycast"
  tasks:
    - name: Find all .plist files in mac-backup-config directory
      ansible.builtin.find:
        paths: "{{ mac_config_dir }}"
        patterns: "*.plist"
        recurse: no
      register: config_files

    - name: Copy .plist files to {{ ansible_env.HOME }}/test
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "{{ ansible_env.HOME }}/test/{{ item.path | basename }}"
        remote_src: yes
        force: yes
      loop: "{{ config_files.files }}"

    - name: Kill affected apps to apply changes
      ansible.builtin.shell: "killall {{ item }}"
      loop: "{{ apps_to_kill }}"
      ignore_errors: yes  # Ignore if app isn’t running

    - name: Restart affected apps to apply changes
      ansible.builtin.shell: open -a {{ item }}        
      loop: "{{ apps_to_restart }}"
      ignore_errors: yes  # Ignore if app isn’t running