---
# Use this script to download safe mac config domains
# to use in the mac-setup.yml playbook
- name: Backup safe macOS defaults including key bindings and hardware settings
  hosts: localhost
  vars_files:
    - mac-setup-vars.yml
  vars:
    backup_dir: "{{ ansible_env.HOME }}/macos_config_backup"
    proj_dir: " {{ ansible_env.HOME }}/git-projects/personal/dev-setup"
    ansible_pw_file: "ansible-vault-pw.env"
  tasks:
  # Store the output in a file that can be stored in git to be copied and imported
    - name: Create backup directory
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
        mode: "0700"

    - name: Export safe defaults
      ansible.builtin.shell: "defaults read {{ item.domain }} > {{ backup_dir }}/{{ item.domain | replace('.', '_') }}.txt"
      loop: "{{ safe_domains }}"
      args:
        creates: "{{ backup_dir }}/{{ item.domain | replace('.', '_') }}.txt"

    - name: Encrypt backups with Ansible Vault
      ansible.builtin.shell: "ansible-vault encrypt {{ backup_dir }}/{{ item.domain | replace('.', '_') }}.txt --vault-password-file {{ proj_dir }}/{{ ansible_pw_file }}"
      loop: "{{ safe_domains }}"
      when: ansible_vault_enabled | default(false)