---
- name: Master playbook to set up development station
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Debug pull directory
      ansible.builtin.debug:
        msg: "Using pull dir: {{ pull_dir }}"

# Run all the child playbooks
# Detect Homebrew prefix to use for all future playbooks
- ansible.builtin.import_playbook: define-brew-prefix.yml

# # Setup terminal and git for dev station
# - ansible.builtin.import_playbook: terminal-setup.yml
# - ansible.builtin.import_playbook: git-setup.yml

# # Setup dev station using Homebrew
# - ansible.builtin.import_playbook: homebrew-setup.yml

# # Setup terminal for dev station
# - ansible.builtin.import_playbook: raycast-setup.yml
# - ansible.builtin.import_playbook: mac-setup.yml