- name: Setup raycast for ease of navigation
  hosts: localhost
  vars_files:
    - vault.yml
  vars:
    rayconfig_filename: "config.rayconfig"  
    raycast_config_url: "https://raw.githubusercontent.com/etgonehomie/dev-setup/main/{{ rayconfig_filename }}"
    raycast_local_filepath: "{{ ansible_env.HOME }}/{{ rayconfig_filename }}"
  tasks:
    - name: Download and store the encrypted raycast config file from GitHub
      get_url:
        url: "{{ raycast_config_url }}"
        dest: "{{ raycast_local_filepath }}"
    # - name: Import Raycast configuration
    #   ansible.builtin.script: |
    #     #!/usr/bin/osascript
    #     tell application "Raycast"
    #       activate
    #       tell application "System Events"
    #         keystroke "Import Settings"  # Type command
    #         delay 1
    #         keystroke return  # Select command
    #         delay 1
    #         keystroke return  # Trigger import
    #         delay 1
    #         keystroke "{{ rayconfig_file }}"  # Use variable directly
    #         delay 1
    #         keystroke return  # Import
    #         delay 1
    #         keystroke "{{ raycast_pw }}"  # Use vault var
    #         delay 1
    #         keystroke return  # Finish import
    #       end tell
    #     end tell
    #   args:
    #     executable: /usr/bin/osascript
    # - name: Remove the Raycast config file
    #   ansible.builtin.file:
    #   path: "{{ raycast_local_filepath }}"
    #   state: absent