- name: Setup raycast for ease of navigation
  hosts: localhost
  vars_files:     # relative path to current playbook
    - vars.yml
    - vault_password.yml
  vars:
    raycast_config_url: "{{ playbook_dir }}/raycast_config.rayconfig"
    applescript_url: "{{ playbook_dir }}/raycast_import.applescript"
    applescript_jinja_url: "{{ applescript_url }}.j2"

  tasks:
    - name: Generate Raycast import script from jinja template {{ applescript_jinja_url }}
      ansible.builtin.template:
        src: " {{ applescript_jinja_url }}"
        dest: "{{ applescript_url }}"
        mode: '0700'  # Executable permissions
      register: script_file

    - name: Debug verification
      ansible.builtin.debug:
        var: "{{ script_file }}"

    # - name: Run Raycast import applescript using config {{ raycast_config_url }}
    #   ansible.builtin.command: /usr/bin/osascript {{ script_file.dest }}