- name: Setup raycast for ease of navigation
  hosts: localhost
  vars_files:
    - vault.yml
  vars:
    rayconfig_filename: "raycast_config.rayconfig"  
    applescript_filename: "raycast_import.applescript"
    
    applescript_url: "https://raw.githubusercontent.com/etgonehomie/dev-setup/refs/heads/main/{{ applescript_filename }}.j2"
    raycast_config_url: "https://raw.githubusercontent.com/etgonehomie/dev-setup/main/{{ rayconfig_filename }}"

    raycast_local_filepath: "{{ ansible_env.HOME }}/{{ rayconfig_filename }}"
    applescript_local_filepath: "{{ ansible_env.HOME }}/{{ applescript_filename }}"
  tasks:
    - name: Download and store the encrypted raycast config file from GitHub
      get_url:
        url: "{{ raycast_config_url }}"
        dest: "{{ raycast_local_filepath }}"

    - name: Generate Raycast import script from template
      ansible.builtin.template:
        src: "{{ applescript_url }}"
        dest: "/tmp/{{ applescript_filename }}"
        mode: '0700'  # Executable permissions
      register: script_file

    - name: Run Raycast import script
      ansible.builtin.command: /usr/bin/osascript {{ script_file.dest }}

    - name: Remove the Raycast config file
      ansible.builtin.file:
        path: "{{ raycast_local_filepath }}"
        state: absent

    - name: Clean up temporary script
      ansible.builtin.file:
        path: "{{ script_file.dest }}"
        state: absent