---
# mac config safe domains
mac_safe_domains:  
  # UI Settings
  - "com.apple.dock"              # dock settings
  - "com.apple.finder"            # finder preferences
  - "com.apple.systemuiserver"    # menu bar settings
  - "com.apple.menuextra.clock"   # menubar clock settings
  - "com.apple.screensaver"       # screen saver settings
  - "com.apple.terminal"          # terminal settings

  # Input Devices
  - "com.apple.keyboard"                  # keyboard settings
  - "com.apple.HIToolbox"                 # system keyboard hotkeys
  - "com.apple.symbolichotkeys"           # other keyboard hotkeys
  - "com.apple.AppleMultitouchTrackpad"   # built-in trackpad settings
  - "com.apple.driver.AppleHIDMouse"      # bluetooth mouse settings
  - "com.apple.driver.AppleBluetoothMultitouch.trackpad" # bluetooth trackpad settings
  
  # Workflow tools
  - "com.raycast.macos"   # raycast hotkeys
  - "com.apple.spaces"    # mission control settings

  # Display/Power settings
  - "com.apple.PowerManagement" 
  - "com.apple.CoreBrightness"    # Night shift schedule
  - "com.apple.BezelServices"     # Display brightness settings
  
  # Other Settings
  - "com.apple.desktopservices"       # desktop and finder behavior
  - "com.apple.universalaccess"       # accessibility settings
  - "com.apple.notificationcenterui"  # notification settings